### PR TITLE
Update xdccget.pl with queue management and search

### PR DESCRIPTION
**Pull request by obfuscoder**
Update xdccget.pl with some queue management and search capabilities. (pausing, retries, max parallel downloads).
Rework of help output.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
there still seems to be some error in travis:
```
* -!- Irssi: warning settings_get(xdccget_config_path) : not found
* -!- Irssi: warning settings_get(xdccget_max_downloads) : not found
* XDCCGET - Warning: Could open queue file for loading from /home/travis/.irssi/xdccget.queue: No such file or directory
```

**Comment by obfuscoder** [comment]
I intended to keep the warnings to see when the configs could not be loaded. On second startup they should not be seen anymore as the files will be there then.

**Comment by ailin-nemui** [comment]
At least for `-!- Irssi: warning settings_get` these are an incorrect usage of Irssi API. You **must** settings_add_* all the settings you are going to *get* on, and also before you get them

**Comment by obfuscoder** [comment]
Used settings_add for all the settings to remove the warnings and set defaults.

**Pull request merged**
