### PR TITLE
Fix appearance / user formatting of awaybar

### PR DESCRIPTION
**Pull request by dreamcat4**
Source: https://github.com/ronilaukkarinen/weed

### CODE REVIEW

**Comment by dequis** [comment]
I'm not sure I understand this change properly.

What about users that don't have AWL?

What about users that upgrade this script through, say, scriptassist, and don't have that format entry?

**Comment by dreamcat4** [comment]
Hi @dequis. Thanks for looking at this PR.

1. Yes that is a good point and sorry that my instruction is so limited like that. It is due to my own lack of knowledge / in-experience. As I simply don't know enough about statusbars. That instruction is cpoed from the instructions / documentation of the Weed theme (link provided in commit msg).

Yes it would certainly benefit to make a better or more generic instruction, including for irssi's standard away bar. The help text is just a supplementary usage infos which is fine to reject entirely if you wish. Just thought it would be better / more helpful than nothing at all.

2. Yes that situation is fine. I have tested without the variable set. So that is same thing for any user who was upgrading from previous version. They will see no difference in the output. The previous version prints / outputs an unformatted text. So will this version if the variable isn't user-set. Nothing is getting broken with that. AFAIKT the scripts original author seemed to try make in the commented line a specific theme setting string, but he gave up on it. So then this PR fixes that problem and explains to the user with an example how they can customize it.

**Comment by ailin-nemui** [comment]
There are some problems:
- you cannot change abstracts using /format, so the instruction you added is wrong about that
- as I explained to you on IRC your awl_shared_sbar setting is wrong
- the /sbar command is also incorrect (should be awl_shared instead of awl_0)
- I don't think this adv_windowlist specific instructions belong in that script
- Also, previously the script would show "Away: ...", with your change it will *only* show the away reason
nevertheless I think it would be fine to make the format configurable in general

**Comment by dreamcat4** [comment]
> nevertheless I think it would be fine to make the format configurable in general

Well great. That was the main thing.

> you cannot change abstracts using /format, so the instruction you added is wrong about that

OK so now I'm not entirely sure how to achieve the new user setting since you said that. If:

```
/format sb_awaybar "%1%Waway: ${0-}"
```

is wrong.

Well no hurry. One of us is bound to come back and figure it out eventually.

**Comment by ailin-nemui** [comment]
I will close this misleading PR, please reopen if you can fix the issues mentioned in here

**Pull request closed without merging**
