### PR TITLE
Add weechat_relay

### PR DESCRIPTION
**Pull request by tslocum**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
I will close this for now, it doesn't seem to be ready

**Comment by tslocum** [comment]
While it works using SSL websockets on my setup @ailin-nemui wasn't able to connect to his.  I tried to contact the devs via IRC unsuccessfully.  If they do respond I'll update.

**Comment by ailin-nemui** [comment]
it would be better if you can coordinate submission to scripts.irssi.org with the devs. also your code has issues (see red X)

**Comment by tslocum** [comment]
Sorry, I thought I had made myself clear when we chatted in IRC.  I didn't write this script, I just cleaned up a few pieces and fixed the issues I had on my system.  Apparently there are other issues with different setups.

**Pull request closed without merging**
