### PR TITLE
Added iquiz.pl & iquiz_en.pl

### PR DESCRIPTION
**Pull request by wilkowy**
iQuiz is a quiz script featuring five types of games: classic Dizzy, Mieszacz, Familiada, Multi (Familiada without teams) and Pomieszany.

iquiz.pl - original script (Polish)
iquiz_en.pl - English translation

### CODE REVIEW

**Comment by wilkowy** [comment]
I see some checks about open/close and using comma failed, but the script is working fine for 5 years now.

**Comment by ailin-nemui** [comment]
hi @wilkowy , thanks for your submission. we have decided to require some best practices for all scripts that go to scripts.irssi.org and I hope you can find the time to implement them. This doesn't mean there is any *fault* with your script per se.

In the questionable case, it should be as simple as changing

    (open(my $fh, $fname))

to

    (open(my $fh, "<", $fname))

in your script. If the green checkmark appears instead of the red cross then we're good to go.

Thanks for your understanding

**Comment by wilkowy** [comment]
Sure, no problem. What about constructs like `print(something), return if (error_condition);`? They also gave check fails. Should I rewrite the postfix?

As I'm not fully familiar with GH yet - I have to close this pull and make a new one, right?

**Comment by dequis** [comment]
>Sure, no problem. What about constructs like `print(something), return if (error_condition);`? They also gave check fails. Should I rewrite the postfix?

The error says "Comma used to separate statements". You could just use semicolons instead of comma.

[More details here](https://metacpan.org/pod/Perl%3A%3ACritic%3A%3APolicy%3A%3AValuesAndExpressions%3A%3AProhibitCommaSeparatedStatements)

>As I'm not fully familiar with GH yet - I have to close this pull and make a new one, right?

No need to, you can just push more commits to the same branch and this PR will update.

**Comment by wilkowy** [comment]
> The error says "Comma used to separate statements". You could just use semicolons instead of comma.

No, that is completely different case. `do(something), return if (error_condition);` is equivalent for `if (error_condirion) { do(something); return; }` The comma is used there on purpose - to execute both commands one by one (not a real list separator). I just made a one-liner shortcut. However if this is confusing for someone or the travis validator than I'll rewrite this as well.

**Comment by ailin-nemui** [comment]
you can also ignore the , issue, you only need to change the "open"

**Comment by wilkowy** [comment]
God damn it I've messed now.

**Pull request closed without merging**
