### PR TITLE
[ack][#7] add ack.pl

### PR DESCRIPTION
**Pull request by bw1**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@IsaacG

**Comment by bw1** [comment]
@rcaputo

**Comment by IsaacG** [comment]
Uh... am I supposed to be giving some sort of input here? If you're looking for signoff to use my changes, go for it. Beyond that, feel free to ping me in #irssi.

**Comment by rcaputo** [comment]
I'm fine with this.

**Pull request merged**
