### PR TITLE
[print_signals.pl] New version 1.2

### PR DESCRIPTION
**Pull request by madduck**
Changelog:

* Unload signal handlers when script is unloaded
* Update list of signals from upstream

### CODE REVIEW

**Comment by ailin-nemui** [comment]
I think irssi auto-removes all handlers on unload anyway :-P

**Comment by madduck** [comment]
unloading v1.0 of this script segfaults my Irssi, hence I wrote this.

**Comment by bw1** [comment]
### v1.0
```
75  # curl -s https://raw.githubusercontent.com/irssi/irssi/master/docs/signals.txt | sed -rne 's,^ ",",p'
91  "command "<cmd>, char *args, SERVER_REC, WI_ITEM_REC
138 "ctcp msg "<cmd>, SERVER_REC, char *args, char *nick, char *addr, char *target
141 "ctcp reply "<cmd>, SERVER_REC, char *args, char *nick, char *addr, char *target
147 "server cap ack "<cmd>, SERVER_REC
148 "server cap nak "<cmd>, SERVER_REC
153 "event "<cmd>, SERVER_REC, char *args, char *sender_nick, char *sender_address
157 "redir "<cmd>, SERVER_REC, char *args, char *sender_nick, char *sender_address
171 "dcc ctcp "<cmd>, char *args, DCC_REC
174 "dcc reply "<cmd>, char *args, DCC_REC
```

**Comment by madduck** [comment]
I don't understand your comment, @bw1. The list is up to date.

**Comment by bw1** [comment]
in list are invalid signals like `# curl` or  `command <cmd>`

<https://github.com/bw1/scripts.irssi.org/commit/244a664ff73333bec2c2ff9a32a62deb813ea377>

**Comment by bw1** [comment]
and that was not always a problem: 

<https://app.travis-ci.com/github/bw1/sc_print_signals>

<https://github.com/bw1/sc_print_signals>

@ailin-nemui

**Comment by madduck** [comment]
> in list are invalid signals like `# curl` or `command <cmd>`

Ah, I get it now. Well, I cannot see `# curl` in the list, but I can definitely see the `<cmd>` problem. And I think your patch is probably the way to go, as there is no way to enumerate those hooks.

**Comment by madduck** [comment]
@bw1 I've imported the relevant part of your commit.

**Pull request merged**
