### PR TITLE
[duckduckgo] add duckduckgo.pl

### PR DESCRIPTION
**Pull request by bw1**

### CODE REVIEW

**Comment by vague666** [comment]
You really shouldn't parse html with regular expressions. Mojolicious makes this easy and has a built-in eventloop

**Comment by vague666** [comment]
I wrote a simple sample script, make what you want out of it :)
https://vague.se/pastes/ddg_async.pl

**Comment by bw1** [comment]
nice
but the ddg function blocks irssi

**Comment by vague666** [comment]
Which is why I wrote do what you want out of it :) it needs to fork or be run through something like IO::Async::Loop::Glib

**Pull request merged**
