### PR TITLE
Updated tinyurl.pl to work with recent perl and tinyurl.com versions

### PR DESCRIPTION
**Pull request by efuce**
Updated tinyurl.pl to work with more recent versions of perl. Fixed the url matching regex to work with the current layout of tinyurl.com.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
Maybe use Www::Shorten::TinyUrl instead?

**Comment by efuce** [comment]
Thanks for the tip. I did not known about WWW::Shorten::TinyUrl. Updated the pull request.

**Comment by ailin-nemui** [comment]
btw you do not need to update scripts.yaml

**Comment by efuce** [comment]
Thanks for informing me. I will remember that for any future commits.

**Pull request merged**
