### PR TITLE
[fnotify] Add own messages to fnotify writes

### PR DESCRIPTION
**Pull request by mrda**
fnotify allows you to do things like turn on blinkenlights when you are
hilighted in messages. Adding your own messages allows you to turn off
any local notifications once you respond.

Sample of how to do this is at
https://github.com/mrda/junkcode/blob/master/irssi-notify.sh

### CODE REVIEW

**Comment by bw1** [comment]
@purpleidea

**Comment by bw1** [comment]
it would be an asset
a config option for the new behavior

**Comment by ailin-nemui** [comment]
@mrda do you think you could make this an option (like /set fnotify_showself ON) ?

**Comment by mrda** [comment]
@ailin-nemui Can you point me at an example of how to create a config value?  Thanks.

**Comment by bw1** [comment]
[guide](https://github.com/shabble/irssi-docs/wiki/Guide#Use-Settings-for-Customisation)

**Comment by ailin-nemui** [comment]
should be like this:

before signal_add:
```
Irssi::settings_add_bool('misc', 'fnotify_own', 0);
```

and in your signal handler, use:
```
if (Irssi::settings_get_bool('fnotify_own')) {
    ...
}
```

and to enable your custom feature:
```
/set fnotify_own ON
```
in Irssi

**Comment by bw1** [comment]
Irssi::settings_get_bool(key)
Irssi::settings_add_bool(section, key, def)

**Comment by bw1** [comment]
thx

**Pull request merged**
