### PR TITLE
[mouse] Add xterm-256color support the mouse script

### PR DESCRIPTION
**Pull request by ChainsawBaby**

### CODE REVIEW

**Comment by soliton-** [comment]
The closing slash for the regex is now missing.

**Comment by ChainsawBaby** [comment]
Woops, I’ll fix

**Comment by bw1** [comment]
see line 34
```
33  	url     	=> 'http://wouter.coekaerts.be/irssi/',
34  	changed  	=> '2009-05-16',
35  );
```

inform the creator:
@coekie

**Comment by ChainsawBaby** [comment]
@bw1 I've sent an email to @coekie to inform him of the update

**Pull request merged**
