### PR TITLE
[mouse] Support kitty terminal

### PR DESCRIPTION
**Pull request by ntgraff**
expand the check of supported terminals to include the [kitty](https://sw.kovidgoyal.net/kitty/) terminal

### CODE REVIEW

**Comment by ailin-nemui** [comment]
I'm not sure if this is correct. what is the output of `echo $TERM ` I in kitty?

**Comment by ntgraff** [comment]
`xterm-kitty`

**Comment by ailin-nemui** [comment]
ok, odd choice

**Comment by ailin-nemui** [comment]
please increase $VERSION

**Comment by ailin-nemui** [comment]
@coekie

**Pull request merged**
