### PR TITLE
Add smshilight

### PR DESCRIPTION
**Pull request by zonidjan**
Send hilights (and queries including the current nick) via SMS, using Twilio.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
hi @zonidjan , please move your script in the  `scripts` subfolder!

**Comment by zonidjan** [comment]
Whoops, sorry about that! Wasn't paying enough attention. Should be good now.

**Comment by ailin-nemui** [comment]
hi again. thanks for contributing to the scripts archive. Please follow our strict coding requirement that the first line of your script should be `use strict;` and the script should be compatible with Perl's strict mode. Also you still need to remove the other copy of your script in the root (on command line, `git rm yourscript`)

**Comment by ailin-nemui** [comment]
:-)

**Pull request merged**
