### PR TITLE
[ircsec] view the missing of blowfish

### PR DESCRIPTION
**Pull request by bw1**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
is this hard dependency or will it autoload perl blowfish module as long as it is installed?

**Comment by bw1** [comment]
autoload by Crypt::CBC via default config
and eval hiden the error message

```
60      eval {
61         $cipher = Crypt::CBC->new( -key             => $key,
62                                    -cipher          => $algo,
63                                    -iv              => '$KJh#(}q',
64                                    -literal_key     => 0,
65                                    -padding         => 'space',
66                                    -header          => 'randomiv'
67                                  );
68  
69      };
```

```
199 Irssi::settings_add_str($IRSSI{name}, 'ircsec_default_cipher', 'Blowfish');
```

**Comment by ailin-nemui** [comment]
`use Crypt::Blowfish` is NOT required

instead the error needs to be un-hidden so people know they must install it (if it is missing)

**Comment by bw1** [comment]
eval is removed

**Pull request merged**
