### PR TITLE
Adding some of my scripts to the repo and update to timezones.pl

### PR DESCRIPTION
**Pull request by vague666**

### CODE REVIEW

**Comment by dequis** [comment]
```
                                  LOAD  HDR  CRIT  SCORE  PASS
                       intercept   ✔     ✔     ✔     2     ✔   
                      notifyquit   ✔     ✔     ✔     2     ✔   
                 tabcompletenick   ✔     ✘     ✘    17     ✘   
                       timezones   ✔     ✔     ✘     9     ☡   
```

Also dammit vague, write decent commit messages please

**Comment by ailin-nemui** [comment]
- you need to change `my` to `our` in tabcompletenick on `$VERSION` and `%IRSSI`
- please make timezones `use strict`

**Comment by ailin-nemui** [comment]
My guess is, you will need to `use Irssi;` as well or this script doesn't load as it seems.

--- timezones.pl

FATAL: SCRIPT FAILED TO LOAD	

*-!- Irssi: Error in script timezones:

*Undefined subroutine &Irssi::statusbar_item_register called at timezones.pl line 68.

**Comment by dequis** [comment]
You didn't fix the commit message :(

**Pull request merged**
