### PR TITLE
Add replace.pl

### PR DESCRIPTION
**Pull request by jeto**
Script to replace something said with regular expressions.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
Did you know trigger.pl?

**Comment by jeto** [comment]
Yes. Tried it but couldn't get it to replace anything even with the example copy pasted. Probably just my incompetence but I wrote a simpler one for my needs.

**Comment by ailin-nemui** [comment]
You could add loading and saving of replaces

**Comment by jeto** [comment]
Planning on that

**Comment by avar** [comment]
I love the idea that you wrote this after getting PTSD from one too many Rick Rolls :)

**Pull request merged**
