### PR TITLE
Automatically load and unload scripts

### PR DESCRIPTION
**Pull request by culb**
Automatically load and unload scripts as they are added, deleted, or
modified

### CODE REVIEW

**Comment by ailin-nemui** [comment]
hi, someone already submitted such a script as autorun_scripts.pl

**Comment by culb** [comment]
That is mine. I didn't know someone put it on here. If any code of mine is going to be used it should be under a BSD license. I don't like the prints in it and use vars should be "our". It would be nice if my code was uploaded as I had it.

**Comment by culb** [comment]
I had not added a version or anything to it because I was not ready to make a pull to irssi. I would appreciate that the script be removed.

**Comment by ailin-nemui** [comment]
@culb can you add the missing name attribute in your version of the script so it passes the test?

**Comment by vague666** [comment]
Hi,
yes the script is based on your script, but it's improved from what it was, and you fail to mention the missing Linux::Inotify2 dependency in File::ChangeNotify, that's my experience at least since I was forced to manually install the module for the script to be at all usable
I looked for you when I uploaded the script but there was no nightfrog to be found at the time

**Comment by dequis** [comment]
So I guess this can be solved in this same pull request, @culb should just "git rm" the other file and integrate the relevant improvements from vague's version:

* [ ] Mention the Linux::Inotify2 possibly-optional dependency and its performance implications
* [ ] Either `follow_symlinks => 1,` and reading from the autorun directory VS reading from the scripts directory?
* [ ] `timeout_add` or `timeout_add_once`?
* [ ] Remove the prints (or make them optional? seems nice to know if it's working)
* [ ] Add a `name` attribute to `%IRSSI`

@vague666 Do you care about the licensing stuff or is it okay to ignore that you put GPLv2 in there and just use BSD like it was intended?

**Comment by vague666** [comment]
I don't care about licensing, the code I got from nightfrog didn't have a license as far as I know, I wouldn't touch that stuff if it was specified so do whatever you like

**Comment by ailin-nemui** [comment]
@culb

**Comment by ailin-nemui** [comment]
Please reopen once you have addressed our concerns

**Pull request closed without merging**
