### PR TITLE
[ignore_topics] Add script for ignoring topic messages.

### PR DESCRIPTION
**Pull request by itsjohncs**
/ignore does not work for this, though there is a bug report open to
fix that.

### CODE REVIEW

**Comment by bw1** [comment]
this script modify the channel sync.
it remove the output of event 332 and event 333
and ignore not a topic change

#### rfc1459 
```
        332     RPL_TOPIC
                        "<channel> :<topic>"

                - When sending a TOPIC message to determine the
                  channel topic, one of two replies is sent.  If
                  the topic is set, RPL_TOPIC is sent back else
                  RPL_NOTOPIC.
```


#### rfc1459 
```
 :Wiz TOPIC #test :New topic     ;User Wiz setting the topic.

```

**Comment by itsjohncs** [comment]
The description and name are set, what specifically are you asking to be changed?

**Comment by bw1** [comment]
this script ignore only part of the topic messages.

a better description is wanted

**Comment by itsjohncs** [comment]
I've decided to use another IRC client and won't be taking the time to get this PR merged. Anyone is welcome to steal this from me and push it through however.

**Pull request closed without merging**
