### PR TITLE
Added desktop-notify 1.0.0

### PR DESCRIPTION
**Pull request by ftonello**
This script sends notification using the Desktop Notifications Specification.

It depends on libnofity, perl-glib-object-introspection and perl-html-parser
packages.

### CODE REVIEW

**Comment by ftonello** [comment]
The build system only failed because it doesn't have one of the dependencies, which is [Glib::Object::Introspection](https://metacpan.org/pod/Glib::Object::Introspection). So it should be fine to merge with no problem.

**Comment by ailin-nemui** [comment]
mhm, weird, I'm not too familiar with Glib but on my local system it doesn't work. I get this error:
```
-!- Irssi v0.8.18-g4af3a47 - http://www.irssi.org
Too late to run INIT block at Glib/Object/Introspection.pm line 257.
 
-!- Irssi: Error in script desktop_notify:
Bareword "Notify::uninit" not allowed while "strict subs" in use at desktop-notify.pl line 56.
Bareword "setup_changed" not allowed while "strict subs" in use at desktop-notify.pl line 100.
```
any idea? might be a broken local setup, I'll try to reinstall some parts

**Comment by ftonello** [comment]
Hi @ailin-nemui,

Yes. I know why it's broken, I will update this pull-request.

**Comment by ftonello** [comment]
@ailin-nemui The last version I sent doesn't show the errors any more, but it still shows the late INIT call, which doesn't affect the functionality of the script since it still works just fine.

**Comment by ailin-nemui** [comment]
ok, as part of your PR can you please add your script here https://github.com/irssi/scripts.irssi.org/blob/gh-pages/_testing/config.yml#L44 with a comment `# fails test due to missing gobject-introspection in travis`

**Comment by ftonello** [comment]
Done. This should be it for this 1.0.0 version.

**Comment by ailin-nemui** [comment]
thanks

**Pull request merged**
