### PR TITLE
script to toggle hidden levels in windows

### PR DESCRIPTION
**Pull request by vague666**
Requires PR https://github.com/irssi/irssi/pull/746

### CODE REVIEW

**Comment by vague666** [comment]
Settings:
window_hidden_levels - levels to hide/show with below commands
Included commands:
/toggle_levels - hide/show levels in active window
/show_levels_all - show levels in all windows
/hide_levels_all - hide levels in all windows

**Comment by ailin-nemui** [comment]
do you want to have the dump_window_hash debug function in the published script?

**Comment by vague666** [comment]
I'm still working on the script, I'll probably remove it yeah

**Comment by ailin-nemui** [comment]
I would probably stick with the Irssi::command since I don't like the setter yet, plus that would make this script which already seems useful, work on 1.1.x (any api changes would have to wait for 1.2, probably)

**Pull request merged**
