### PR TITLE
Add hilightcmd

### PR DESCRIPTION
**Pull request by ramnes**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
thanks for your contribution. I'm always a bit wary about calling system, what do you think about running the message parameter through String::ShellQuote?

**Comment by ailin-nemui** [comment]
@ramnes ping

**Comment by ramnes** [comment]
Hey @ailin-nemui,

Thanks for merging, and sorry that I didn't participate more. Since I'm not a Perl developer at all, I wanted to take a look at your proposition more seriously before answering, but never took the time.

This is a hack I made to answer a need I had and that a lot of friends have too, and it works. If I ever enhance it to follow your advices, I'll make sure to update this PR or make a new one!

**Comment by ailin-nemui** [comment]
Someone else actually finished your work, see #259

**Comment by ramnes** [comment]
Yeah, I just seen that. Thanks a lot @tslocum!

**Pull request merged**
