### PR TITLE
[CI] populate 'selfcheckcmd'

### PR DESCRIPTION
**Pull request by bw1**
cycle

### CODE REVIEW

**Comment by ailin-nemui** [comment]
why do you need this in the scripts.yml?

**Comment by bw1** [comment]
for find scripts with a selfcheck enviornment

**Comment by ailin-nemui** [comment]
@bw1 if you run this on a git clone of the scripts, you could just run it on every script. Originally at least, scripts.yml was meant for scriptassist

@irssi/developers anyone has an idea about this?

I don't like the design very much. Also the scripts are calling `Irssi::command("selfcheckhelperscript $result")`. I'm not sure if I like that either.

But I do like the idea of testing scripts!

**Comment by vague666** [comment]
I'd prefer making sure the script is loaded and then calling the symbol directly, ie 
```
my $f = Irssi::Script::selfcheckscript->can('selfcheckhelperscript');
$f->($args) if $f;
```

**Comment by bw1** [comment]
*  run it on every script 

that's the hard way and we hide the info

**Comment by ailin-nemui** [comment]
Or maybe, just `Irssi::signal_add("print text"` in the selfcheckhelperscript

then `print "scriptname: self check result: $some_result"`;

that way you don't have to call a function.

**Comment by ailin-nemui** [comment]
to find the scripts without putting too much info into the public scripts.yml, you can also try this: I think it might work (untested)

```
git clone -b ci-artefacts git@github.com:irssi/scripts.irssi.org scripts-ci
cd scripts-ci
perl \
    -MFile::Basename \
    -MYAML=LoadFile \
    -E'
        @docs = map {
            my ($doc) = @{ LoadFile($_) };
            $doc->{filename} = basename(dirname($_));
            $doc
        } @ARGV;
        for (@docs) {
            say $_->{filename} 
                if exists $_->{selfcheckcmd};
        }
    ' \
    -- \
    Test/*/info.yml
```

**Comment by bw1** [comment]
or
```
	my $ft= read_text("$p/$fn",":latin1");
	if ( $ft =~ m/selfcheckcmd/ ) {
```
[:link:->:scroll:](https://github.com/bw1/check-irssi-scripts-selftest/blob/master/ModScanner.pl#L48)

**Comment by bw1** [comment]
##  self check end :football:
```
 my $schs_version = $Irssi::Script::selfcheckhelperscript::VERSION;
 Irssi::command("selfcheckhelperscript $s") if ( defined $schs_version );
```
or

```
my $schs_version = $Irssi::Script::selfcheckhelperscript::VERSION;
Irssi::signal_emit("selfcheckend","ok") if ( defined $schs_version );
```
or

...

**Comment by ailin-nemui** [comment]
* you cannot use signal_emit without signal_register in all scripts, so I would not use your idea (2)

* what do you think about vague's variant?

* If you use the "print 'special text'" idea, you do not need "IF / VERSION"

**Comment by bw1** [comment]
### self check end
#### old
```    
Irssi::command("selfcheckhelperscript $s");
```
```
22:22 Users min:129 max:1879 check
22:22 -!- Irssi: Unknown command: selfcheckhelperscript
```
#### in the moment
```
my $schs_version = $Irssi::Script::selfcheckhelperscript::VERSION;
Irssi::command("selfcheckhelperscript $s") if ( defined $schs_version );
```
hint by @vague666 

#### version vague
```
my $f = Irssi::Script::selfcheckscript->can('selfcheckhelperscript');
$f->($args) if $f;
```

also two lines and a not marked  jump in

**Pull request closed without merging**
