### PR TITLE
adding xdcc.pl

### PR DESCRIPTION
**Pull request by julescarbon**
This script adds functionality for running an XDCC server in irssi.  People can request DCC sends over CTCP. Trusted users can also upload files.

More info: http://asdf.us/xdcc/

### CODE REVIEW

**Comment by ailin-nemui** [comment]
travis points out an issue on lines 332-334, where you have a `+` (numeric addition) instead of `.` (string concatenation) while adding a suffix to the size

**Comment by julescarbon** [comment]
Good catch, thanks - Let me know if you need me to do anything else

**Comment by ailin-nemui** [comment]
I have observed the maintainers requiring you to "squash" your commits into a single one for example with `git reset --soft origin/gh-pages && git commit && git push -f`

**Comment by GeertHauwaerts** [comment]
I've manually merged this request.

**Pull request closed without merging**
