### PR TITLE
Fixed the usercount script

### PR DESCRIPTION
**Pull request by floriansimon1**
Used prefixes instead of Irssi variables because Irssi variables weren't working

### CODE REVIEW

**Comment by ailin-nemui** [comment]
"admin" and "room owner" are ircx specific and not present in the irssi hash. Only these non-standard modes (`q`, `a`, etc) will require `prefixes` or `chr $_->{other}`. Sadly, they are not always mapped to `~` and `&`, but also to `*` or `!`. Some servers even have `-` which is less than `+`. Thus, it might be neat to compare the modes to `$server->isupport('prefix')` if the server supports `isupport`

`serverop` is quite different, it's a global server operator and *not* visible in the prefixes (`*` in `WHO`). Your change is removing this feature from the script.

**Comment by c0ding** [comment]
@ailin-nemui The IRCd specific modes could be turned into settings then, couldn't they. Because having an incomplete script in to repo makes no sense to me. I've tried @floriansimon1 's changes and they actually work, which isn't the case of the initial script.

**Comment by GeertHauwaerts** [comment]
@ailin-nemui close?

**Comment by ailin-nemui** [comment]
@floriansimon1 it would be great if you could make the script keep the original IRCop functionality (do not touch that part of the code in function), but make it count the other prefixes. I would use a hash table for that, so that you can say  `$special{ $nick->{other} }++`. However, you need to implement the proper look-up. To do that, you can parse the result from `$server->isupport("prefix")` --  the format is `(`*`list of mode letters`*`)`*`list of characters`*. It is sorted by "power", but the only things known for sure are those actually in the standard, i,e `o` and `v`. And use the default value of `(qohv).@%+` (as required by the extended ircx standard). Then you can employ a mode letter to type table, but there is nothing really fixed to my knowledge. The actual prefixes in use vary widely, for example I found this [bug report](http://colloquy.info/project/ticket/772) on colloquy regarding to that issue. 

| letter | meaning | |
|---|-----------|----------------------------|
| u | founder | if it appears before o |
| q | owner | |
| a | admin | |
| o | op | |
| h | half-op | |
| v | voice | |
| w | member | |
| u | member | if it appears after v |
| ! | services | |

if that is too complicated for you, maybe just make it count "others" instead without going too much into detail

**Comment by floriansimon1** [comment]
I can't code in Perl. My previous pull request was merely a way of contributing to your repo what worked for c0da.

**Pull request closed without merging**
